//
//  FrancoSphereImports.swift
//  FrancoSphere v6.0
//
//  Auto-generated by fix script
//

@_exported import Foundation
@_exported import SwiftUI
@_exported import Combine

// Ensure all core types are accessible
public typealias MaintenanceTask = CoreTypes.MaintenanceTask
public typealias TaskCategory = CoreTypes.TaskCategory
public typealias TaskUrgency = CoreTypes.TaskUrgency
public typealias WeatherCondition = CoreTypes.WeatherCondition
public typealias BuildingMetrics = CoreTypes.BuildingMetrics
public typealias FrancoWorkerAssignment = CoreTypes.FrancoWorkerAssignment
public typealias ComplianceStatus = CoreTypes.ComplianceStatus
public typealias TaskProgress = CoreTypes.TaskProgress
